---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: z4ce/rootfs-goyamlenv
inputs:
  - name: pcf-pipelines
  - name: terraform-state
  - name: config
outputs:
  - name: config-out
params:
  secrets: ((aws_secrets))
run:
  path: pcf-pipelines/install-pcf/aws/tasks/config-director/task.sh
