---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs
inputs:
  - name: pcf-pipelines 
  - name: terraform-state
  - name: ami
outputs:
  - name: terraform-state-output
params:
  secrets: ((aws_secrets))
run:
  path: pcf-pipelines/install-pcf/aws/tasks/prepare-aws/task.sh
