---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs
inputs:
  - name: pcf-pipelines 
  - name: config
  - name: terraform-state
params:
  secrets: ((aws_secrets))
run:
  path: pcf-pipelines/install-pcf/aws/tasks/prepare-rds/task.sh
