---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: z4ce/rootfs-goyamlenv
inputs:
  - name: config
  - name: pcf-pipelines 
  - name: terraform-state
outputs:
  - name: terraform-state-output
params:
  secrets: ((aws_secrets))
run:
  path: pcf-pipelines/install-pcf/aws/tasks/wipe-env/task.sh
